name: Release to Homebrew

on:
  release:
    types: [created]

jobs:
  upload-asset:
    runs-on: ubuntu-latest
    name: upload-asset
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./dockerctx
          asset_name: dockerctx
          asset_content_type: application/octet-stream
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Release DockerCTX to my Stenstromen/homebrew-tap
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: Stenstromen
          homebrew_tap: homebrew-tap

          formula_folder: Formula

          github_token: ${{ secrets.GITHUB_TOKEN }}

          commit_owner: Stenstromen
          commit_email: contact@stenstromen.se

          install: 'bin.install "dockerctx" => "dockerctx"'
        

          
